[package]
name = "limbo"
version = "0.1.0"
edition = "2021"

[dependencies]
glow = "0.12.3"
jpeg-encoder = "0.5.1"
sdl2 = "0.35.2"
v4l = "0.14.0"
zune-jpeg = "0.3.17"

[profile.dev.package.zune-jpeg]
opt-level = 3
